CLI_DIST = packages/cli/dist/index.js
EXAMPLES = $(wildcard tests/examples/*.poly)
# Everything generated by a build lives under build/ -- one directory to
# ignore, and nothing writable inside dist/. That separation is not cosmetic:
# deno compile embeds its own output directory, so when the binaries sat in
# dist/bin each run re-embedded the last one and the artefacts grew to 9.6 GB
# (see devel/singlebin202609.md).
BUILD_DIR = build
OUTDIR = $(BUILD_DIR)/test

# The CLI ships as a bun-compiled single binary, so tests and the example
# sweep run under Bun by default: the test runtime must match the shipping
# runtime, or engine differences slip through untested (see
# devel/bun-migration202609.md). Dependencies are still installed with pnpm --
# Bun consumes the pnpm-built node_modules as-is.
BUN ?= $(shell command -v bun 2>/dev/null || echo $(HOME)/.bun/bin/bun)
CLI = $(BUN) run $(CLI_DIST)

# Kept as the retreat path and as a second engine (V8) for the binary.
DENO ?= $(shell command -v deno 2>/dev/null || echo $(HOME)/.deno/bin/deno)

# Single-binary output
BIN_DIR = $(BUILD_DIR)/bin
# `bun build --compile` needs a Bun-only entry: it embeds only what its bundler
# sees, and the 22 MB kernel is resolved at runtime. See packages/cli/bun-entry.ts.
BUN_ENTRY = packages/cli/bun-entry.ts
# Release assets keep the conventional target triples so download URLs and
# install scripts do not change; bun's own --target names are mapped in the
# rules below. bun also appends .exe for windows targets.
# macOS は Apple Silicon のみ。x86_64-apple-darwin は 2026-09-03 に外した
# (Intel Mac 向け。復活させるなら release.yml の matrix に macos-13 を戻す)。
TARGETS = x86_64-unknown-linux-gnu aarch64-apple-darwin x86_64-pc-windows-msvc

# Derived, not hardcoded: a new package with a test script joins the sweep
# automatically. Hardcoded lists are how live/@polyscript/ui silently fell out
# of make build/test for four months (see devel/TODO.md 2026-08-26).
TEST_PKGS = $(patsubst %/package.json,%,$(shell grep -l '"test"' packages/*/package.json))

.PHONY: build test test-node fulltest lint example binary binary-all binary-test \
        binary-deno release-check release release-publish

build:
	pnpm -r build

# Everything below that consumes packages/*/dist depends on `build`, not on the
# dist file. A file prerequisite only fires when the file is MISSING, so a dist
# that exists but is stale was silently accepted: edit packages/core/src, run
# `make test`, and cli + browser go green against the previous build while
# core's own suite runs the new source. Nothing errors -- the run is just a lie.
#
# `build` is .PHONY so it always runs (~5s, tsc is incremental). That is the
# price of the guarantee. Do not "optimise" this back into a file prerequisite.
#
# Why cross-package work needs dist at all: packages import each other by name,
# so resolution goes through core's `exports`, which publishes only ./dist.
# See DEVEL.md "開発中にソースから実行する".

# Still vitest, now driven by Bun. `bun test` (the native runner) is the
# eventual target -- see devel/bun-migration202609.md Phase 4.
test: build
	@for p in $(TEST_PKGS); do \
		echo "=== $$p ==="; \
		(cd $$p && $(BUN) x vitest run) || exit 1; \
	done

# Secondary: the historical Node run. live's dev server is Node/Vite, and the
# browser bundle runs on user engines anyway, so keeping one Node pass around
# is cheap insurance for the non-CLI consumers.
test-node: build
	pnpm test

# No `build` prerequisite on purpose: the regression suite lives in
# packages/core and imports ../src directly, so it never touches dist.
# Measured: passes with packages/core/dist absent.
fulltest:
	cd packages/core && EXAMPLE=1 $(BUN) x vitest run -t "B-Rep regression" --reporter=verbose

lint:
	pnpm lint

example: build
	@mkdir -p $(OUTDIR)
	@for f in $(EXAMPLES); do \
		echo "=== $$(basename $$f) ==="; \
		$(CLI) build $$f -o $(OUTDIR)/$$(basename $$f .poly).stl || true; \
	done

# Compile the shippable single binary (current platform).
binary: build
	@mkdir -p $(BIN_DIR)
	$(BUN) build --compile $(BUN_ENTRY) --outfile $(BIN_DIR)/poly
	@ls -la $(BIN_DIR)/poly

# Cross-compile for every release target.
binary-all: build
	@mkdir -p $(BIN_DIR)
	@for t in $(TARGETS); do \
		case $$t in \
		  x86_64-unknown-linux-gnu) bt=bun-linux-x64;; \
		  aarch64-apple-darwin)     bt=bun-darwin-arm64;; \
		  x86_64-pc-windows-msvc)   bt=bun-windows-x64;; \
		  *) echo "no bun target for $$t"; exit 1;; \
		esac; \
		echo "=== $$t ($$bt) ==="; \
		$(BUN) build --compile --target=$$bt \
			$(BUN_ENTRY) --outfile $(BIN_DIR)/poly-$$t || exit 1; \
	done
	@ls -la $(BIN_DIR)/

# Retreat path: the pre-2026-09-02 Deno binary, kept so the V8 build stays
# reproducible. The binaries live outside dist/ now, so deno compile no longer
# re-embeds its own output (that is how the artefacts once reached 9.6 GB);
# --exclude keeps build/ out regardless, since it is under the compile root.
binary-deno: build
	@mkdir -p $(BIN_DIR)
	$(DENO) compile --no-check --allow-all --exclude $(BUILD_DIR) \
		--output $(BIN_DIR)/poly-deno packages/cli/dist/index.js
	@ls -la $(BIN_DIR)/poly-deno

# Test what actually ships, two ways. (1) Build every example with the compiled
# binary: exercises bun build --compile's asset embedding (the .wasm inside the
# binary), which `bun run` cannot cover. (2) Check the binary's `info --json`
# against the regression snapshots: `make fulltest` drives the core library and
# never touches the CLI, which is how `poly info` shipped a compound where the
# library fused (4 solids on 00_polyscript_logo) with every test green.
binary-test: binary
	@mkdir -p $(OUTDIR)
	@fail=0; for f in $(EXAMPLES); do \
		if ! $(BIN_DIR)/poly build $$f -o $(OUTDIR)/bin_$$(basename $$f .poly).stl >/dev/null 2>&1; then \
			echo "FAIL: $$(basename $$f)"; fail=1; \
		fi; \
	done; \
	if [ $$fail -eq 0 ]; then echo "binary-test: all $(words $(EXAMPLES)) examples build"; else exit 1; fi
	POLY=$(BIN_DIR)/poly $(BUN) tests/binary_check.ts

# ---------------------------------------------------------------------------
# Release
# ---------------------------------------------------------------------------
# Procedure: devel/release202609.md. `make release` builds and verifies the
# artifacts; publishing is a separate explicit step because it is the only
# irreversible one.

VERSION = $(shell node -p "require('./packages/cli/package.json').version")
RELEASE_DIR = $(BUILD_DIR)/release

# Everything that must be green before cutting a release. Runs the test suite
# on the shipping runtime (Deno) and, crucially, binary-test: the compiled
# binary building every example, which is the only check that covers
# deno compile's asset embedding (the .wasm inside the binary).
release-check: build
	$(MAKE) test
	$(MAKE) fulltest
	$(MAKE) lint
	$(MAKE) binary-test
	@echo
	@echo "release-check OK — version $(VERSION)"

# Cross-compiled binaries, archives and checksums, ready to upload.
release: release-check binary-all
	@rm -rf $(RELEASE_DIR) && mkdir -p $(RELEASE_DIR)
	@for t in $(TARGETS); do \
		case $$t in *windows*) exe=poly.exe; src=$(BIN_DIR)/poly-$$t.exe;; \
		                  *) exe=poly;     src=$(BIN_DIR)/poly-$$t;; esac; \
		stage=$$(mktemp -d); \
		cp $$src $$stage/$$exe; chmod +x $$stage/$$exe; \
		case $$t in \
		  *windows*) (cd $$stage && zip -q poly.zip $$exe) && \
		             mv $$stage/poly.zip $(RELEASE_DIR)/poly-$(VERSION)-$$t.zip;; \
		  *) tar czf $(RELEASE_DIR)/poly-$(VERSION)-$$t.tar.gz -C $$stage $$exe;; \
		esac; \
		rm -rf $$stage; \
	done
	@cd $(RELEASE_DIR) && sha256sum * > SHA256SUMS
	@echo
	@ls -la $(RELEASE_DIR)/
	@echo
	@echo "Version reported by the built binary: $$($(BIN_DIR)/poly --version)"
	@echo "Check that against $(VERSION), then: make release-publish"

# The only irreversible step. Kept separate so the artifacts above can be
# inspected first.
release-publish:
	@test -d $(RELEASE_DIR) || { echo "run 'make release' first" >&2; exit 1; }
	gh release create v$(VERSION) $(RELEASE_DIR)/* \
		--title "poly v$(VERSION)" \
		--notes "PolyScript CLI v$(VERSION) — single-binary builds produced with \`bun build --compile\`. No runtime install needed. Verify downloads against SHA256SUMS."
