/**
 * PolyScript B-Rep regression tests (TypeScript side).
 *
 * Compares shape output (bbox, volume, topology) from the TypeScript evaluator
 * against golden snapshots generated by the Python implementation.
 *
 * Uses the real occt-wasm kernel (not mocked).
 *
 * Skipped by default. Set EXAMPLE=1 to run:
 *   EXAMPLE=1 npx vitest run
 */

import { describe, it, expect, beforeAll } from 'vitest';
import fs from 'node:fs';
import path from 'node:path';

import { parse } from '../src/parser.js';
import { Evaluator } from '../src/evaluator.js';
import type { Value } from '../src/eval/types.js';
import { initOC } from '../src/ocp-kernel/init.js';
import { shapeInfo } from '../src/ocp-kernel/analysis.js';
import type { ShapeInfo } from '../src/ocp-kernel/analysis.js';
import type { OC, Shape } from '../src/ocp-kernel/types.js';

// ---------------------------------------------------------------------------
// Paths
// ---------------------------------------------------------------------------

const SNAPSHOTS_DIR = path.resolve(__dirname, '../../../tests/snapshots');
const EXAMPLES_DIR = path.resolve(__dirname, '../../../tests/examples');

// ---------------------------------------------------------------------------
// Load snapshots
// ---------------------------------------------------------------------------

interface Snapshot {
  bbox: { min: [number, number, number]; max: [number, number, number] };
  volume: number;
  topology: { faces: number; edges: number; vertices: number };
}

interface MetaFile {
  generator: string;
  tolerance: { bbox: number; volume_percent: number };
}

function loadMeta(): MetaFile {
  return JSON.parse(fs.readFileSync(path.join(SNAPSHOTS_DIR, 'meta.json'), 'utf-8'));
}

function loadSnapshot(filename: string): Snapshot | null {
  return JSON.parse(fs.readFileSync(path.join(SNAPSHOTS_DIR, `${filename}.json`), 'utf-8'));
}

function listSnapshotFiles(): string[] {
  return fs.readdirSync(SNAPSHOTS_DIR)
    .filter(f => f.endsWith('.poly.json'))
    .sort()
    .map(f => f.replace(/\.json$/, ''));
}

const { tolerance } = loadMeta();
const snapshotNames = listSnapshotFiles();

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

/**
 * Build an import resolver that reads .poly files from the examples directory.
 */
function makeImportResolver(examplesDir: string): (p: string) => string | null {
  return (importPath: string) => {
    const candidates = [
      path.join(examplesDir, `${importPath}.poly`),
      path.join(examplesDir, importPath),
    ];
    for (const candidate of candidates) {
      if (fs.existsSync(candidate)) {
        return fs.readFileSync(candidate, 'utf-8');
      }
    }
    return null;
  };
}

/**
 * Evaluate a .poly source and extract the final shape.
 * Handles multiple top-level shapes via implicit union (same as Evaluator.getShape).
 */
function evaluateAndGetShape(oc: OC, source: string, importResolver: (p: string) => string | null): Shape | null {
  const program = parse(source);
  const evaluator = new Evaluator({
    oc,
    importResolver,
    parseFn: parse,
  });
  const result: Value = evaluator.evaluate(program);
  return evaluator.getShape(result);
}

/**
 * Assert shape info matches the expected snapshot within tolerances.
 */
function assertShapeInfo(filename: string, info: ShapeInfo, expected: Snapshot): void {
  const bboxTol = tolerance.bbox; // 0.1
  const axes = ['x', 'y', 'z'];

  // BBox: absolute tolerance
  for (let i = 0; i < 3; i++) {
    expect(
      Math.abs(info.bbox.min[i] - expected.bbox.min[i]),
      `${filename}: bbox min[${axes[i]}] = ${info.bbox.min[i]} vs expected ${expected.bbox.min[i]}`,
    ).toBeLessThanOrEqual(bboxTol);
    expect(
      Math.abs(info.bbox.max[i] - expected.bbox.max[i]),
      `${filename}: bbox max[${axes[i]}] = ${info.bbox.max[i]} vs expected ${expected.bbox.max[i]}`,
    ).toBeLessThanOrEqual(bboxTol);
  }

  // Volume: relative tolerance
  const volTolFraction = tolerance.volume_percent / 100; // 0.01
  const volDiff = Math.abs(info.volume - expected.volume);
  const volRef = Math.max(Math.abs(expected.volume), 1e-12);
  expect(
    volDiff / volRef,
    `${filename}: volume ${info.volume.toFixed(4)} vs expected ${expected.volume} (${((volDiff / volRef) * 100).toFixed(2)}% diff)`,
  ).toBeLessThanOrEqual(volTolFraction);

  // Topology: exact match
  expect(info.topology.faces, `${filename}: face count`).toBe(expected.topology.faces);
  expect(info.topology.edges, `${filename}: edge count`).toBe(expected.topology.edges);
  expect(info.topology.vertices, `${filename}: vertex count`).toBe(expected.topology.vertices);
}

// ---------------------------------------------------------------------------
// Test suite
// ---------------------------------------------------------------------------

describe.skipIf(!process.env.EXAMPLE)('B-Rep regression (vs Python snapshots)', () => {
  let oc: OC;

  beforeAll(async () => {
    oc = await initOC();
  }, 120_000);

  const importResolver = makeImportResolver(EXAMPLES_DIR);

  for (const filename of snapshotNames) {
    const expected = loadSnapshot(filename);

    // Skip null snapshots (library files like gear.poly)
    if (expected === null) {
      it.skip(`${filename} (library file, no snapshot)`, () => {});
      continue;
    }

    // Every snapshot must match. There is deliberately no allowance for a
    // known-failing case: a divergence from the Python oracle is either a bug
    // to fix or a snapshot to regenerate, never a test left red.
    it(filename, () => {
      const filePath = path.join(EXAMPLES_DIR, filename);
      const source = fs.readFileSync(filePath, 'utf-8');
      const shape = evaluateAndGetShape(oc, source, importResolver);
      expect(shape, `${filename}: evaluator returned no shape`).not.toBeNull();
      const info = shapeInfo(oc, shape!);
      assertShapeInfo(filename, info, expected);
    });
  }
});
