// Usage: cd polyscript-ts && bun tests/gen_context_model.ts [--check] [file]
//
// Regenerates the tables of the poly skill's context model
// (`.claude/skills/poly/references/context-model.md`) from the
// validator's CONTEXT_OPS and context.ts's nextContext. Only the part between
// the BEGIN/END markers is written; the prose and the examples around it stay
// hand-written.
//
// The file used to be copied by hand and drifted: it listed no `rotate` or
// `mirror` for Face / Wire, which is how an AI came to write
// `arc ... | rotate 90 0 0 | sweep`. --check exits 1 when the file is stale;
// packages/core/test/context-model-doc.test.ts runs the same comparison.
import { readFileSync, writeFileSync } from 'node:fs';
import { resolve } from 'node:path';
import { CONTEXT_OPS, type Context } from '../packages/core/src/validator.ts';
import { nextContext, OP_KEYWORD, type PipelineContext } from '../packages/core/src/context.ts';

export const BEGIN = '<!-- BEGIN generated by polyscript-ts/tests/gen_context_model.ts -->';
export const END = '<!-- END generated -->';

export const DEFAULT_FILE = resolve(
  import.meta.dirname, '../../.claude/skills/poly/references/context-model.md',
);

/** Contexts in the order the document presents them, with the line under each heading. */
const CONTEXTS: [Context, string][] = [
  ['3D', ''],
  ['Face', ' — 領域(`rect` `circle` `sketch` `text` …、2Dブーリアンや `offset` の結果)'],
  ['Wire', ' — 曲線(`wire [...]` `line` `arc` `bezier` `spline` `helix`)。閉じていても面積を持たない'],
  ['Workplane', ''],
  ['FaceSelection', ''],
  ['EdgeSelection', ''],
  ['VertexSelection', ''],
  ['PointSelection', ''],
];

/** AST op types that are all "draw a 2D shape here". */
const PRIM2D = new Set([
  'Implicit2DPrimitive', 'RectExpr', 'CircleExpr', 'EllipseExpr', 'PolylineExpr', 'PolygonExpr', 'TextExpr',
]);

function keyword(type: string): string {
  if (PRIM2D.has(type)) return '2D primitive';
  if (type === 'Implicit3DPrimitive') return '3D primitive';
  return OP_KEYWORD[type] ?? type;
}

/** Transitions whose target depends on the operand, not only on the context. */
const OPERAND_DEPENDENT: Record<string, string> = {
  '2D primitive': 'Face(`rect` `circle` `sketch` …) / Wire(`wire [...]` `arc` …)',
  place: '配置した形状の型(Face / Wire)',
};

function transition(type: string, from: Context[]): string {
  const pairs = from.map(c => [c, nextContext(c as PipelineContext, type)] as const);
  if (pairs.every(([c, n]) => n === c)) return '維持';
  const targets = new Set(pairs.map(([, n]) => n));
  if (targets.size === 1 && pairs.every(([c]) => c !== [...targets][0])) return [...targets][0];
  const changed = pairs.filter(([c, n]) => n !== c).map(([c, n]) => `${c} → ${n}`);
  return `維持(ただし ${changed.join(', ')})`;
}

export function renderContextModel(): string {
  const out: string[] = [BEGIN, '', '## コンテキストごとに使える操作', ''];
  for (const [ctx, gloss] of CONTEXTS) {
    const kws = [...new Set([...CONTEXT_OPS[ctx]].map(keyword))].sort();
    out.push(`**${ctx}**${gloss}`, '', kws.map(k => `\`${k}\``).join(', '), '');
  }

  out.push('## 遷移', '', '「維持」= 入力のコンテキストをそのまま引き継ぐ。「ただし」は入力によって変わる場合。', '');
  out.push('| 操作 | 使える場所 | 遷移先 |', '|---|---|---|');
  const byKeyword = new Map<string, { type: string; from: Context[] }>();
  for (const [ctx] of CONTEXTS) {
    for (const type of CONTEXT_OPS[ctx]) {
      const kw = keyword(type);
      const entry = byKeyword.get(kw) ?? { type, from: [] };
      if (!entry.from.includes(ctx)) entry.from.push(ctx);
      byKeyword.set(kw, entry);
    }
  }
  for (const kw of [...byKeyword.keys()].sort()) {
    const { type, from } = byKeyword.get(kw)!;
    out.push(`| \`${kw}\` | ${from.join(', ')} | ${OPERAND_DEPENDENT[kw] ?? transition(type, from)} |`);
  }
  out.push('', END);
  return out.join('\n');
}

/** The generated block currently in `text`, or null when it has no markers. */
export function currentBlock(text: string): string | null {
  const a = text.indexOf(BEGIN);
  const b = text.indexOf(END);
  return a < 0 || b < a ? null : text.slice(a, b + END.length);
}

if (import.meta.main) {
  const args = process.argv.slice(2);
  const check = args.includes('--check');
  const file = args.find(a => !a.startsWith('--')) ?? DEFAULT_FILE;
  const text = readFileSync(file, 'utf8');
  const block = currentBlock(text);
  if (block === null) {
    console.error(`${file}: no ${BEGIN} ... ${END} block`);
    process.exit(2);
  }
  const fresh = renderContextModel();
  if (block === fresh) {
    console.log(`${file}: up to date`);
  } else if (check) {
    console.error(`${file}: stale -- run 'bun tests/gen_context_model.ts'`);
    process.exit(1);
  } else {
    writeFileSync(file, text.replace(block, fresh));
    console.log(`${file}: regenerated`);
  }
}
