/**
 * Fold skills/poly into a TypeScript module the CLI can carry.
 *
 * `poly` ships as a single bun-compiled binary, so it cannot read files that
 * sit next to it -- there is no "next to it". Embedding the text means
 * `poly skill install` works offline, and the skill can never be a version out
 * of step with the commands it tells an agent to run.
 *
 *   bun scripts/gen-skill-data.ts          # write packages/cli/src/skill-data.ts
 *   bun scripts/gen-skill-data.ts --check  # fail if it is stale (for CI)
 */
import { readdirSync, readFileSync, statSync, writeFileSync } from 'node:fs';
import { join, relative, sep } from 'node:path';

const root = new URL('..', import.meta.url).pathname;
const skillDir = join(root, 'skills', 'poly');
const out = join(root, 'packages', 'cli', 'src', 'skill-data.ts');

function walk(dir: string): string[] {
  const found: string[] = [];
  for (const name of readdirSync(dir).sort()) {
    const full = join(dir, name);
    if (statSync(full).isDirectory()) found.push(...walk(full));
    else if (name.endsWith('.md')) found.push(full);
  }
  return found;
}

const all = walk(skillDir).map((full) => ({
  // POSIX separators: this string becomes a path on the installing machine,
  // which is not necessarily the one that built the binary.
  path: relative(skillDir, full).split(sep).join('/'),
  text: readFileSync(full, 'utf8')
}));

// locales/<lang>/... is carried per language and installed one at a time;
// everything else goes to every installation.
const files = all.filter((f) => !f.path.startsWith('locales/'));
const locales: Record<string, { path: string; text: string }[]> = {};
for (const f of all) {
  const m = f.path.match(/^locales\/([^/]+)\/(.+)$/);
  if (!m) continue;
  (locales[m[1]] ??= []).push({ path: `references/${m[2]}`, text: f.text });
}

const body = `// GENERATED by scripts/gen-skill-data.ts -- do not edit.
// Source: skills/poly/. Re-run \`bun scripts/gen-skill-data.ts\` after changing it.

/** What every installation gets, keyed by its path below skills/poly/. */
export const SKILL_FILES: Record<string, string> = {
${files.map((f) => `\t${JSON.stringify(f.path)}: ${JSON.stringify(f.text)}`).join(',\n')}
};

/**
 * The language-specific half, by locale.
 *
 * One of these is installed alongside SKILL_FILES. The paths are the ones the
 * installed tree uses, so the skill refers to references/vocabulary.md
 * whichever language is chosen.
 */
export const SKILL_LOCALES: Record<string, Record<string, string>> = {
${Object.entries(locales)
  .map(([lang, fs]) => `\t${JSON.stringify(lang)}: {\n${fs.map((f) => `\t\t${JSON.stringify(f.path)}: ${JSON.stringify(f.text)}`).join(',\n')}\n\t}`)
  .join(',\n')}
};
`;

if (process.argv.includes('--check')) {
  if (readFileSync(out, 'utf8') !== body) {
    console.error('skill-data.ts is stale. Run: bun scripts/gen-skill-data.ts');
    process.exit(1);
  }
  console.log(`skill-data.ts is current (${files.length} files)`);
} else {
  writeFileSync(out, body);
  console.log(`skill-data.ts: ${files.length} shared + ${Object.keys(locales).length} locales, ${(body.length / 1024).toFixed(0)}KB`);
  for (const f of files) console.log(`  ${f.path}`);
  for (const [lang, fs] of Object.entries(locales)) console.log(`  [${lang}] ${fs.map((f) => f.path).join(', ')}`);
}
